// Code generated by Kitex v1.21.0. DO NOT EDIT.
package userservice

import (
	server "github.com/cloudwego/kitex/server"
	user "github.com/ozline/tiktok/kitex_gen/user"
)

func NewServer(handler user.UserService, opts ...server.Option) server.Server {
	var options []server.Option
	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler user.UserService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
