// Code generated by Kitex v0.12.0. DO NOT EDIT.

package productservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	product "github.com/ozline/tiktok/kitex_gen/product"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateProduct(ctx context.Context, req *product.CreateProductRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error)
	UpdateProduct(ctx context.Context, req *product.UpdateProductRequest, callOptions ...callopt.Option) (r *product.UpdateProductResponse, err error)
	GetProduct(ctx context.Context, req *product.GetProductRequest, callOptions ...callopt.Option) (r *product.GetProductResponse, err error)
	ListProducts(ctx context.Context, req *product.ListProductsRequest, callOptions ...callopt.Option) (r *product.ListProductsResponse, err error)
	CreateSeckill(ctx context.Context, req *product.CreateSeckillRequest, callOptions ...callopt.Option) (r *product.CreateSeckillResponse, err error)
	GetSeckill(ctx context.Context, req *product.GetSeckillRequest, callOptions ...callopt.Option) (r *product.GetSeckillResponse, err error)
	ListSeckill(ctx context.Context, req *product.ListSeckillRequest, callOptions ...callopt.Option) (r *product.ListSeckillResponse, err error)
	DeductStock(ctx context.Context, req *product.DeductStockRequest, callOptions ...callopt.Option) (r *product.DeductStockResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductServiceClient struct {
	*kClient
}

func (p *kProductServiceClient) CreateProduct(ctx context.Context, req *product.CreateProductRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProduct(ctx, req)
}

func (p *kProductServiceClient) UpdateProduct(ctx context.Context, req *product.UpdateProductRequest, callOptions ...callopt.Option) (r *product.UpdateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProduct(ctx, req)
}

func (p *kProductServiceClient) GetProduct(ctx context.Context, req *product.GetProductRequest, callOptions ...callopt.Option) (r *product.GetProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProduct(ctx, req)
}

func (p *kProductServiceClient) ListProducts(ctx context.Context, req *product.ListProductsRequest, callOptions ...callopt.Option) (r *product.ListProductsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListProducts(ctx, req)
}

func (p *kProductServiceClient) CreateSeckill(ctx context.Context, req *product.CreateSeckillRequest, callOptions ...callopt.Option) (r *product.CreateSeckillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSeckill(ctx, req)
}

func (p *kProductServiceClient) GetSeckill(ctx context.Context, req *product.GetSeckillRequest, callOptions ...callopt.Option) (r *product.GetSeckillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSeckill(ctx, req)
}

func (p *kProductServiceClient) ListSeckill(ctx context.Context, req *product.ListSeckillRequest, callOptions ...callopt.Option) (r *product.ListSeckillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSeckill(ctx, req)
}

func (p *kProductServiceClient) DeductStock(ctx context.Context, req *product.DeductStockRequest, callOptions ...callopt.Option) (r *product.DeductStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeductStock(ctx, req)
}
