// Code generated by Kitex v1.21.0. DO NOT EDIT.

package productservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	product "github.com/ozline/tiktok/kitex_gen/product"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateProduct": kitex.NewMethodInfo(
		createProductHandler,
		newProductServiceCreateProductArgs,
		newProductServiceCreateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetProduct": kitex.NewMethodInfo(
		getProductHandler,
		newProductServiceGetProductArgs,
		newProductServiceGetProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListProducts": kitex.NewMethodInfo(
		listProductsHandler,
		newProductServiceListProductsArgs,
		newProductServiceListProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateSeckill": kitex.NewMethodInfo(
		createSeckillHandler,
		newProductServiceCreateSeckillArgs,
		newProductServiceCreateSeckillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSeckill": kitex.NewMethodInfo(
		getSeckillHandler,
		newProductServiceGetSeckillArgs,
		newProductServiceGetSeckillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSeckill": kitex.NewMethodInfo(
		listSeckillHandler,
		newProductServiceListSeckillArgs,
		newProductServiceListSeckillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeductStock": kitex.NewMethodInfo(
		deductStockHandler,
		newProductServiceDeductStockArgs,
		newProductServiceDeductStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	productServiceServiceInfo                = NewServiceInfo()
	productServiceServiceInfoForClient       = NewServiceInfoForClient()
	productServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductService"
	handlerType := (*product.ProductService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.21.0",
		Extra:           extra,
	}
	return svcInfo
}

func createProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceCreateProductArgs)
	realResult := result.(*product.ProductServiceCreateProductResult)
	success, err := handler.(product.ProductService).CreateProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceCreateProductArgs() interface{} {
	return product.NewProductServiceCreateProductArgs()
}

func newProductServiceCreateProductResult() interface{} {
	return product.NewProductServiceCreateProductResult()
}

func getProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceGetProductArgs)
	realResult := result.(*product.ProductServiceGetProductResult)
	success, err := handler.(product.ProductService).GetProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceGetProductArgs() interface{} {
	return product.NewProductServiceGetProductArgs()
}

func newProductServiceGetProductResult() interface{} {
	return product.NewProductServiceGetProductResult()
}

func listProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceListProductsArgs)
	realResult := result.(*product.ProductServiceListProductsResult)
	success, err := handler.(product.ProductService).ListProducts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceListProductsArgs() interface{} {
	return product.NewProductServiceListProductsArgs()
}

func newProductServiceListProductsResult() interface{} {
	return product.NewProductServiceListProductsResult()
}

func createSeckillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceCreateSeckillArgs)
	realResult := result.(*product.ProductServiceCreateSeckillResult)
	success, err := handler.(product.ProductService).CreateSeckill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceCreateSeckillArgs() interface{} {
	return product.NewProductServiceCreateSeckillArgs()
}

func newProductServiceCreateSeckillResult() interface{} {
	return product.NewProductServiceCreateSeckillResult()
}

func getSeckillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceGetSeckillArgs)
	realResult := result.(*product.ProductServiceGetSeckillResult)
	success, err := handler.(product.ProductService).GetSeckill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceGetSeckillArgs() interface{} {
	return product.NewProductServiceGetSeckillArgs()
}

func newProductServiceGetSeckillResult() interface{} {
	return product.NewProductServiceGetSeckillResult()
}

func listSeckillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceListSeckillArgs)
	realResult := result.(*product.ProductServiceListSeckillResult)
	success, err := handler.(product.ProductService).ListSeckill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceListSeckillArgs() interface{} {
	return product.NewProductServiceListSeckillArgs()
}

func newProductServiceListSeckillResult() interface{} {
	return product.NewProductServiceListSeckillResult()
}

func deductStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceDeductStockArgs)
	realResult := result.(*product.ProductServiceDeductStockResult)
	success, err := handler.(product.ProductService).DeductStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceDeductStockArgs() interface{} {
	return product.NewProductServiceDeductStockArgs()
}

func newProductServiceDeductStockResult() interface{} {
	return product.NewProductServiceDeductStockResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateProduct(ctx context.Context, req *product.CreateProductRequest) (r *product.CreateProductResponse, err error) {
	var _args product.ProductServiceCreateProductArgs
	_args.Req = req
	var _result product.ProductServiceCreateProductResult
	if err = p.c.Call(ctx, "CreateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProduct(ctx context.Context, req *product.GetProductRequest) (r *product.GetProductResponse, err error) {
	var _args product.ProductServiceGetProductArgs
	_args.Req = req
	var _result product.ProductServiceGetProductResult
	if err = p.c.Call(ctx, "GetProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListProducts(ctx context.Context, req *product.ListProductsRequest) (r *product.ListProductsResponse, err error) {
	var _args product.ProductServiceListProductsArgs
	_args.Req = req
	var _result product.ProductServiceListProductsResult
	if err = p.c.Call(ctx, "ListProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSeckill(ctx context.Context, req *product.CreateSeckillRequest) (r *product.CreateSeckillResponse, err error) {
	var _args product.ProductServiceCreateSeckillArgs
	_args.Req = req
	var _result product.ProductServiceCreateSeckillResult
	if err = p.c.Call(ctx, "CreateSeckill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSeckill(ctx context.Context, req *product.GetSeckillRequest) (r *product.GetSeckillResponse, err error) {
	var _args product.ProductServiceGetSeckillArgs
	_args.Req = req
	var _result product.ProductServiceGetSeckillResult
	if err = p.c.Call(ctx, "GetSeckill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSeckill(ctx context.Context, req *product.ListSeckillRequest) (r *product.ListSeckillResponse, err error) {
	var _args product.ProductServiceListSeckillArgs
	_args.Req = req
	var _result product.ProductServiceListSeckillResult
	if err = p.c.Call(ctx, "ListSeckill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeductStock(ctx context.Context, req *product.DeductStockRequest) (r *product.DeductStockResponse, err error) {
	var _args product.ProductServiceDeductStockArgs
	_args.Req = req
	var _result product.ProductServiceDeductStockResult
	if err = p.c.Call(ctx, "DeductStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
