// Code generated by Kitex v1.21.0. DO NOT EDIT.

package orderservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	order "github.com/ozline/tiktok/kitex_gen/order"
)

type Client interface {
	Seckill(ctx context.Context, req *order.SeckillRequest, callOptions ...callopt.Option) (r *order.SeckillResponse, err error)
	GetOrder(ctx context.Context, req *order.GetOrderRequest, callOptions ...callopt.Option) (r *order.GetOrderResponse, err error)
	ListOrders(ctx context.Context, req *order.ListOrdersRequest, callOptions ...callopt.Option) (r *order.ListOrdersResponse, err error)
	PayOrder(ctx context.Context, req *order.PayOrderRequest, callOptions ...callopt.Option) (r *order.PayOrderResponse, err error)
	CancelOrder(ctx context.Context, req *order.CancelOrderRequest, callOptions ...callopt.Option) (r *order.CancelOrderResponse, err error)
}

func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) Seckill(ctx context.Context, req *order.SeckillRequest, callOptions ...callopt.Option) (r *order.SeckillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Seckill(ctx, req)
}

func (p *kOrderServiceClient) GetOrder(ctx context.Context, req *order.GetOrderRequest, callOptions ...callopt.Option) (r *order.GetOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, req)
}

func (p *kOrderServiceClient) ListOrders(ctx context.Context, req *order.ListOrdersRequest, callOptions ...callopt.Option) (r *order.ListOrdersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrders(ctx, req)
}

func (p *kOrderServiceClient) PayOrder(ctx context.Context, req *order.PayOrderRequest, callOptions ...callopt.Option) (r *order.PayOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PayOrder(ctx, req)
}

func (p *kOrderServiceClient) CancelOrder(ctx context.Context, req *order.CancelOrderRequest, callOptions ...callopt.Option) (r *order.CancelOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}
