// Code generated by Kitex v1.21.0. DO NOT EDIT.
package orderservice

import (
	server "github.com/cloudwego/kitex/server"
	order "github.com/ozline/tiktok/kitex_gen/order"
)

func NewServer(handler order.OrderService, opts ...server.Option) server.Server {
	var options []server.Option
	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler order.OrderService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
